# Generated by Django 4.1.2 on 2022-11-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_videos", "0002_alter_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
    ]
