# Generated by Django 4.1.2 on 2022-11-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_videos", "0003_alter_video_titulo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=30)),
                ("cor", models.CharField(max_length=30)),
            ],
        ),
    ]
