# Generated by Django 4.1.2 on 2022-11-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db_videos", "0004_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="categoriaId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db_videos.categoria",
            ),
        ),
    ]
